name: DockerBuildAndPush
on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  setup-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker-compose
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build Docker images
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ducthinh1606/training_app_thinh:latest
          file: ./backend/Dockerfile
          context: ./backend
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache