name: TestWorker
on:
  push:
  pull_request:
    branches:
      - develop
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    container:
      image: ducthinh1606/training_app_thinh:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Composer
        run: composer install

      - name: Setup .env
        run: cp .env.example .env

      - name: Key generate
        run: php artisan key:generate

      - name: Run PHPUnit
        run: php artisan test